# Generated by Django 3.2 on 2021-05-12 07:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='university',
            name='department_availability',
        ),
        migrations.RemoveField(
            model_name='university',
            name='places',
        ),
        migrations.AddField(
            model_name='exchangereview',
            name='datetime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Jour de publication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='review_number',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Nombre de Review'),
        ),
        migrations.AlterField(
            model_name='departementinsa',
            name='name',
            field=models.CharField(choices=[('BB', 'Biosciences Biochimie et Biotechnologie'), ('BIM', 'Bioinformatique et Modélisation'), ('GCU', 'Génie Civil et Urbanisme'), ('GE', 'Génie Electrique'), ('GEN', 'Génie Energétique et Environnement'), ('GI', 'Génie Industriel'), ('GM', 'Génie Mécanique'), ('IF', 'Informatique'), ('SGM', 'Science et Génie Matériaux'), ('TC', 'Télécommunications, Services et Usages')], max_length=100, unique=True, verbose_name='Département INSA'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='department',
            field=models.CharField(choices=[('BB', 'Biosciences Biochimie et Biotechnologie'), ('BIM', 'Bioinformatique et Modélisation'), ('GCU', 'Génie Civil et Urbanisme'), ('GE', 'Génie Electrique'), ('GEN', 'Génie Energétique et Environnement'), ('GI', 'Génie Industriel'), ('GM', 'Génie Mécanique'), ('IF', 'Informatique'), ('SGM', 'Science et Génie Matériaux'), ('TC', 'Télécommunications, Services et Usages')], default='TC', max_length=30, verbose_name='Département INSA'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='university',
            name='courses_difficulty',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=2, null=True, verbose_name='Note sur la difficulté des cours'),
        ),
        migrations.AlterField(
            model_name='university',
            name='courses_interest',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=2, null=True, verbose_name="Note sur l'intérêt des cours"),
        ),
        migrations.AlterField(
            model_name='university',
            name='student_proximity',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=2, null=True, verbose_name='Note sur la proximité sociale des étudiants'),
        ),
        migrations.CreateModel(
            name='PlacesExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Nombre de places')),
                ('department_availability', models.ManyToManyField(to='mobi.DepartementINSA', verbose_name='Disponibilité selon le Département')),
                ('semester', models.ManyToManyField(to='mobi.Semester', verbose_name='Semestres concernés')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placesExchange', to='mobi.university', verbose_name='Université')),
            ],
            options={
                'verbose_name_plural': 'Places disponibles pour des échanges académiques',
            },
        ),
        migrations.CreateModel(
            name='PlacesDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Nombre de places')),
                ('department_availability', models.ManyToManyField(to='mobi.DepartementINSA', verbose_name='Disponibilité selon le Département')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placesDD', to='mobi.university', verbose_name='Université')),
            ],
            options={
                'verbose_name_plural': 'Places disponibles pour des doubles diplômes',
            },
        ),
    ]
