# Generated by Django 3.2 on 2021-06-02 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='rent_average',
        ),
        migrations.RemoveField(
            model_name='exchangereview',
            name='semester_accepted',
        ),
        migrations.RemoveField(
            model_name='university',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='university',
            name='courses_difficulty',
        ),
        migrations.RemoveField(
            model_name='university',
            name='courses_interest',
        ),
        migrations.RemoveField(
            model_name='university',
            name='department_availability',
        ),
        migrations.RemoveField(
            model_name='university',
            name='places',
        ),
        migrations.RemoveField(
            model_name='university',
            name='student_proximity',
        ),
        migrations.AddField(
            model_name='exchangereview',
            name='datetime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Jour de publication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exchangereview',
            name='semester',
            field=models.CharField(blank=True, choices=[('4A-S1', '4A-S1'), ('4A-S2', '4A-S2'), ('5A-S1', '5A-S1'), ('5A-S2', '5A-S2'), ('4A', '4A'), ('5A', '5A')], max_length=30, verbose_name='Semestre de mobilité'),
        ),
        migrations.AddField(
            model_name='university',
            name='rent_average',
            field=models.IntegerField(default=0, null=True, verbose_name='Loyer moyen'),
        ),
        migrations.AlterField(
            model_name='departementinsa',
            name='name',
            field=models.CharField(choices=[('BB', 'Biosciences Biochimie et Biotechnologie'), ('BIM', 'Bioinformatique et Modélisation'), ('GCU', 'Génie Civil et Urbanisme'), ('GE', 'Génie Electrique'), ('GEN', 'Génie Energétique et Environnement'), ('GI', 'Génie Industriel'), ('GM', 'Génie Mécanique'), ('IF', 'Informatique'), ('SGM', 'Science et Génie Matériaux'), ('TC', 'Télécommunications, Services et Usages')], max_length=100, unique=True, verbose_name='Département INSA'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='courses_difficulty',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Difficulté des cours'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='courses_interest',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Intérêt des cours'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='department',
            field=models.CharField(choices=[('BB', 'Biosciences Biochimie et Biotechnologie'), ('BIM', 'Bioinformatique et Modélisation'), ('GCU', 'Génie Civil et Urbanisme'), ('GE', 'Génie Electrique'), ('GEN', 'Génie Energétique et Environnement'), ('GI', 'Génie Industriel'), ('GM', 'Génie Mécanique'), ('IF', 'Informatique'), ('SGM', 'Science et Génie Matériaux'), ('TC', 'Télécommunications, Services et Usages')], default='TC', max_length=30, verbose_name='Département INSA'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse email'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='financial_aid',
            field=models.ManyToManyField(blank=True, to='mobi.FinancialAid', verbose_name='Aides reçus lors de la mobilité'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='student_proximity',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Proximité sociale avec les étudiants'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Année de départ en échange'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('4A-S1', '4A-S1'), ('4A-S2', '4A-S2'), ('5A-S1', '5A-S1'), ('5A-S2', '5A-S2'), ('4A', '4A'), ('5A', '5A')], max_length=100, unique=True, verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='university',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='university',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='Longitude'),
        ),
        migrations.CreateModel(
            name='PlacesExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Nombre de places')),
                ('department_availability', models.ManyToManyField(to='mobi.DepartementINSA', verbose_name='Disponibilité selon le Département')),
                ('semester', models.ManyToManyField(to='mobi.Semester', verbose_name='Semestres concernés')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placesExchange', to='mobi.university', verbose_name='Université')),
            ],
            options={
                'verbose_name_plural': 'Places disponibles pour des échanges académiques',
            },
        ),
        migrations.CreateModel(
            name='PlacesDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Nombre de places')),
                ('department_availability', models.ManyToManyField(to='mobi.DepartementINSA', verbose_name='Disponibilité selon le Département')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placesDD', to='mobi.university', verbose_name='Université')),
            ],
            options={
                'verbose_name_plural': 'Places disponibles pour des doubles diplômes',
            },
        ),
    ]
