# Generated by Django 3.2 on 2021-05-03 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='university',
            name='places',
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DD', 'Double Diplôme'), ('E', 'Echange')], default='E', max_length=100, unique=True, verbose_name='Type de place')),
                ('number', models.IntegerField(blank=True, default=0, verbose_name="Nombre d'étudiants acceptés")),
                ('decoupe', models.BooleanField(default=False)),
                ('duration', models.DecimalField(decimal_places=1, default=0, max_digits=3, null=True, verbose_name='Durée totale disponible en semestres')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='mobi.university', verbose_name='Université')),
            ],
            options={
                'verbose_name_plural': 'Places Disponibles',
            },
        ),
    ]
