# Generated by Django 3.2 on 2021-05-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0002_auto_20210512_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='cost_of_living_average_grade',
        ),
        migrations.RemoveField(
            model_name='city',
            name='cultural_life_average_grade',
        ),
        migrations.RemoveField(
            model_name='city',
            name='night_life_average_grade',
        ),
        migrations.RemoveField(
            model_name='city',
            name='rent_average',
        ),
        migrations.RemoveField(
            model_name='city',
            name='security_average_grade',
        ),
        migrations.RemoveField(
            model_name='exchangereview',
            name='semester_accepted',
        ),
        migrations.RemoveField(
            model_name='university',
            name='courses_difficulty',
        ),
        migrations.RemoveField(
            model_name='university',
            name='courses_interest',
        ),
        migrations.RemoveField(
            model_name='university',
            name='review_number',
        ),
        migrations.RemoveField(
            model_name='university',
            name='student_proximity',
        ),
        migrations.AddField(
            model_name='exchangereview',
            name='semester',
            field=models.CharField(blank=True, choices=[('4A-S1', '4A-S1'), ('4A-S2', '4A-S2'), ('5A-S1', '5A-S1'), ('5A-S2', '5A-S2'), ('4A', '4A'), ('5A', '5A')], max_length=30, verbose_name='Semestre de mobilité'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='financial_aid',
            field=models.ManyToManyField(blank=True, to='mobi.FinancialAid', verbose_name='Aides reçus lors de la mobilité'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('4A-S1', '4A-S1'), ('4A-S2', '4A-S2'), ('5A-S1', '5A-S1'), ('5A-S2', '5A-S2'), ('4A', '4A'), ('5A', '5A')], max_length=100, unique=True, verbose_name='Semestre'),
        ),
    ]
