# Generated by Django 3.2 on 2021-06-05 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0002_auto_20210602_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangereview',
            name='cost_of_living',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note sur le coût de la vie'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='courses_difficulty',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Difficulté des cours'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='courses_interest',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Intérêt par rapport aux cours'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='culture',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note sur la vie culturelle'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='night_life',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note sur la vie nocturne'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='security',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Note de sécurité'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='student_proximity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Proximité sociale avec les étudiants'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='univ_appartment',
            field=models.BooleanField(verbose_name='Appartements disponibles sur le campus'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='visa',
            field=models.TextField(blank=True, null=True, verbose_name='Obtention du visa'),
        ),
    ]
