# Generated by Django 3.2 on 2021-05-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0002_auto_20210504_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='rent_average',
        ),
        migrations.AddField(
            model_name='university',
            name='rent_average',
            field=models.IntegerField(default=0, null=True, verbose_name='Loyer moyen'),
        ),
    ]
