# Generated by Django 3.2 on 2021-06-06 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0002_auto_20210602_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='rent_average',
        ),
    ]
