# Generated by Django 3.2 on 2021-06-06 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0003_auto_20210605_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='rent_average',
        ),
    ]
