# Generated by Django 3.2 on 2021-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0003_auto_20210519_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='university',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=18, null=True, verbose_name='Longitude'),
        ),
    ]
