# Generated by Django 3.2 on 2021-05-26 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobi', '0004_auto_20210525_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangereview',
            name='courses_difficulty',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Difficulté des cours'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='courses_interest',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Intérêt des cours'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='student_proximity',
            field=models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Proximité sociale avec les étudiants'),
        ),
        migrations.AlterField(
            model_name='exchangereview',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Année de départ en échange'),
        ),
    ]
